# Generated by Django 5.2.6 on 2025-10-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_purchasedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
