# Generated by Django 5.2.6 on 2025-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
